name: Deploy GitHub Pages

on:
  push:
    branches:
      - main          # auto deploy on push to main
  workflow_dispatch:  # manual trigger via GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install || echo "No dependencies needed"

      - name: Build (if needed)
        run: echo "Static site ready — no build step"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./       # your site root folder
