name: Deploy GitHub Pages

on:
  push:
    branches:
      - main           # automatic deploy on push
  workflow_dispatch:    # manual trigger option

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Deploy to GitHub Pages (static site)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./       # root folder with index.html
          force_orphan: true
          allow_empty_commit: true
          keep_files: false
          enable_jekyll: false
          exclude_assets: .github
